# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGithubshort():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_githubshort(self):
    self.open_home_page()
    self.login( username="SergeyShorgin", password="Stunt686rider")
    self.logout()

  def logout(self):
    self.driver.find_element(By.CSS_SELECTOR, ".js-feature-preview-indicator-container > .Header-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-signout").click()

  def login(self, username, password):
    self.driver.find_element(By.CSS_SELECTOR, ".HeaderMenu-link:nth-child(2) > font > font").click()
    self.driver.find_element(By.ID, "login_field").send_keys("%s" % username)
    self.driver.find_element(By.ID, "password").send_keys("%s" % password)
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)

  def open_home_page(self):
    self.driver.get("https://github.com/")
    self.driver.set_window_size(2121, 1400)